# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
<<<<<<< HEAD
=======
after_success:
  - Rscript -e 'covr::codecov()'
>>>>>>> 4be24afb0e6488045bb28bda464ac6bf3885ec2c
